Fix build errors with missing header files.
Error:
cyttsp5_regs.h:62:10: fatal error: 'linux/cyttsp5_core.h' file not found


Change-Id: I824cd60cb7cf62f5e57f8850c10e18f95a9777e0
Reviewed-on: https://gerrit.mot.com/2203813
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key